# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'displayConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import deviceConfig
import lanConfig 
import displayConfig 
import wifiConfig 
import systemConfig 
import accountConfig
import das01
import log
import db
import os


class Ui_DisplayWindow(object):
    windows=None
    def ack(self):
        das01.ack=1
        db.updDb.updData(1,"m_mesin","ack",1,"id",1)
    def mute(self):
        db.updDb.updData(1,"m_mesin","mute",0,"id",1)
    def reset(self):
        das01.ack=0
        db.updDb.rstMesin(1)
    def openLog(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = log.Ui_LogWindow()
        self.ui.setupUi(self.window)
        log.Ui_LogWindow.windows=self.window
        self.windows.destroy()
        self.window.show()
    def openHome(self):
        print("gotoHome")
        self.window = QtWidgets.QMainWindow()
        self.ui = das01.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        das01.Ui_MainWindow.windows=self.window
    def openConfig(self):
        self.window = QtWidgets.QMainWindow()
        #print(deviceConfig)
        self.ui = deviceConfig.Ui_ConfigWindow()
        self.ui.setupUi(self.window)
        deviceConfig.Ui_ConfigWindow.windows=self.window
        self.window.show()
        self.windows.destroy()
    def openLan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = lanConfig.Ui_LanWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        lanConfig.Ui_LanWindow.windows=self.window
    def openWifi(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = wifiConfig.Ui_WifiWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        wifiConfig.Ui_WifiWindow.windows=self.window
    def openSystem(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = systemConfig.Ui_SystemWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        systemConfig.Ui_SystemWindow.windows=self.window
    def openAccount(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = accountConfig.Ui_AccountWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        accountConfig.Ui_AccountWindow.windows=self.window



    def setupUi(self, DisplayWindow):
        DisplayWindow.setObjectName("DisplayWindow")
        DisplayWindow.resize(1280, 800)
        max_x=DisplayWindow.width()
        max_y=DisplayWindow.height()
        DisplayWindow.showFullScreen()
        DisplayWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(DisplayWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(30, 100, max_x-60, 371))
        self.listView.setObjectName("listView")
        self.lineEdit_port = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_port.setGeometry(QtCore.QRect(40, 140, max_x-80, 26))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.lineEdit_port.setInputMask("00")
        self.label_form = QtWidgets.QLabel(self.centralwidget)
        self.label_form.setGeometry(QtCore.QRect(40, 120, 97, 20))
        self.label_form.setObjectName("label_form")
        self.lineEdit_size = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_size.setGeometry(QtCore.QRect(40, 190, max_x-80, 26))
        self.lineEdit_size.setObjectName("lineEdit_size")
        self.lineEdit_size.setInputMask("00")
        self.label_form_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_form_2.setGeometry(QtCore.QRect(40, 170, 97, 20))
        self.label_form_2.setObjectName("label_form_2")
        self.pb_save_display = QtWidgets.QPushButton(self.centralwidget)
        self.pb_save_display.setGeometry(QtCore.QRect(40, 380, 191, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_save_display.setFont(font)
        self.pb_save_display.setObjectName("pb_save_display")
        self.pb_save_display.clicked.connect(self.showDialog)

        self.pb_device = QtWidgets.QPushButton(self.centralwidget)
        self.pb_device.setGeometry(QtCore.QRect(30, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_device.setFont(font)
        self.pb_device.setObjectName("pb_device")
        self.pb_device.clicked.connect(self.openConfig)
        
        self.pb_lan = QtWidgets.QPushButton(self.centralwidget)
        self.pb_lan.setGeometry(QtCore.QRect(130, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_lan.setFont(font)
        self.pb_lan.setObjectName("pb_lan")
        self.pb_lan.clicked.connect(self.openLan)

        self.pb_wifi = QtWidgets.QPushButton(self.centralwidget)
        self.pb_wifi.setGeometry(QtCore.QRect(230, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_wifi.setFont(font)
        self.pb_wifi.setObjectName("pb_wifi")
        self.pb_wifi.clicked.connect(self.openWifi)

        self.pb_display_active = QtWidgets.QPushButton(self.centralwidget)
        self.pb_display_active.setGeometry(QtCore.QRect(330, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_display_active.setFont(font)
        self.pb_display_active.setObjectName("pb_display_active")


        self.pb_system = QtWidgets.QPushButton(self.centralwidget)
        self.pb_system.setGeometry(QtCore.QRect(430, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_system.setFont(font)
        self.pb_system.setObjectName("pb_system")
        self.pb_system.clicked.connect(self.openSystem)

        self.pb_account = QtWidgets.QPushButton(self.centralwidget)
        self.pb_account.setGeometry(QtCore.QRect(530, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_account.setFont(font)
        self.pb_account.setObjectName("pb_account")
        self.pb_account.clicked.connect(self.openAccount)

        self.label_device = QtWidgets.QLabel(self.centralwidget)
        self.label_device.setGeometry(QtCore.QRect(30, 80, max_x-60, 31))
        self.label_device.setObjectName("label_device")
        self.label_form_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_form_3.setGeometry(QtCore.QRect(40, 270, 97, 20))
        self.label_form_3.setObjectName("label_form_3")
        self.lineEdit_height = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_height.setGeometry(QtCore.QRect(40, 290, max_x-80, 26))
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.lineEdit_height.setInputMask("0.0")
        self.label_form_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_form_4.setGeometry(QtCore.QRect(40, 220, 97, 20))
        self.label_form_4.setObjectName("label_form_4")
        self.lineEdit_width = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_width.setGeometry(QtCore.QRect(40, 240, max_x-80, 26))
        self.lineEdit_width.setObjectName("lineEdit_width")
        
        self.lineEdit_width.setInputMask("0.0")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 340,  max_x-80, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("10 Seconds",10)
        self.comboBox.addItem("30 Seconds",30)
        self.comboBox.addItem("60 Seconds",60)
        self.comboBox.addItem("5 Minutes",300)
        self.comboBox.addItem("10 Minutes",600) 
        self.comboBox.addItem("15 Minutes",900)
        self.comboBox.addItem("20 Minutes",1200)
        self.comboBox.addItem("30 Minutes",1800)
        self.comboBox.addItem("60 Minutes",3600)
        self.label_form_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_form_5.setGeometry(QtCore.QRect(40, 320, 97, 20))
        self.label_form_5.setObjectName("label_form_5")

        DisplayWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DisplayWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        DisplayWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DisplayWindow)
        self.statusbar.setObjectName("statusbar")
        DisplayWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DisplayWindow)
        QtCore.QMetaObject.connectSlotsByName(DisplayWindow)
        das01.Ui_MainWindow.setupfooter(self,DisplayWindow)
        

    def retranslateUi(self, DisplayWindow):
        _translate = QtCore.QCoreApplication.translate
        DisplayWindow.setWindowTitle(_translate("DisplayWindow", "MainWindow"))
        self.label_form.setText(_translate("DisplayWindow", "Display Port"))
        self.label_form_2.setText(_translate("DisplayWindow", "Font Size"))
        self.pb_save_display.setText(_translate("DisplayWindow", "Save Configuration"))
        self.pb_device.setText(_translate("DisplayWindow", "Device Setting"))
        self.pb_lan.setText(_translate("DisplayWindow", "LAN Setting"))
        self.pb_wifi.setText(_translate("DisplayWindow", "WiFi Setting"))
        self.pb_display_active.setText(_translate("DisplayWindow", "Display Setting"))
        self.pb_system.setText(_translate("DisplayWindow", "System"))
        self.pb_account.setText(_translate("DisplayWindow", "My Account"))
        self.label_device.setText(_translate("DisplayWindow", "   Display Setting "))
        self.label_form_3.setText(_translate("DisplayWindow", "Zoom Height"))
        self.label_form_4.setText(_translate("DisplayWindow", "Zoom Width"))
        cfg= db.readDb.readDataTabel(1,"m_mesin")
        self.lineEdit_port.setText(str(cfg[0]["displayed_port"]))
        self.lineEdit_size.setText(str(cfg[0]["f_size"]))
        self.lineEdit_width.setText(str(cfg[0]["zoom_w"]))
        self.lineEdit_height.setText(str(cfg[0]["zoom_h"]))
        self.label_form_5.setText(_translate("DisplayWindow", "Backlight Saver"))
        #print (cfg)
        index = self.comboBox.findData(int(cfg[0]["display_time"]))
        if index >= 0:
            self.comboBox.setCurrentIndex(index)
        print(index)

    def showDialog(self):
        msgBox = QtWidgets.QMessageBox()
        displayed_port =self.lineEdit_port.text()
        zoom_w         = self.lineEdit_width.text()
        zoom_h         = self.lineEdit_height.text()
        f_size         = self.lineEdit_size.text()   
        display_time   = str(self.comboBox.currentData())
        print(display_time)

        if len(displayed_port)>0 and len(zoom_w)>0 and len(zoom_h)>0 and len(f_size)>0:
            res=db.updDb.updateDisplay(1,displayed_port,zoom_w,zoom_h,f_size,display_time)
            print(res)
            msgBox.setText("Your Data Has been Saved")
            msgBox.setWindowTitle("Status Message")  
            msgBox.setIcon(QtWidgets.QMessageBox.Information)
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
            os.popen("pm2 restart 1")
            returnValue = msgBox.exec()
            
        else:
            msgBox.setText("Your Data is Empty")
            msgBox.setWindowTitle("Status Message")  
            msgBox.setIcon(QtWidgets.QMessageBox.Warning)
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
            returnValue = msgBox.exec()
            print("data is Empty")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DisplayWindow = QtWidgets.QMainWindow()
    ui = Ui_DisplayWindow()
    ui.setupUi(DisplayWindow)
    DisplayWindow.show()
    sys.exit(app.exec_())
