# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'systemConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import deviceConfig 
import lanConfig
import displayConfig 
import wifiConfig 
import systemConfig 
import accountConfig
import das01
import log
import db

class Ui_SystemWindow(object):
    windows =None
    def ack(self):
        das01.ack=1
        db.updDb.updData(1,"m_mesin","ack",1,"id",1)
    def mute(self):
        db.updDb.updData(1,"m_mesin","mute",0,"id",1)
    def reset(self):
        das01.ack=0
        db.updDb.rstMesin(1)
    def openLog(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = log.Ui_LogWindow()
        self.ui.setupUi(self.window)
        log.Ui_LogWindow.windows=self.window
        self.windows.destroy()
        self.window.show()
    def openHome(self):
        print("gotoHome")
        self.window = QtWidgets.QMainWindow()
        self.ui = das01.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        das01.Ui_MainWindow.windows=self.window
    def openConfig(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = deviceConfig.Ui_ConfigWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        deviceConfig.Ui_ConfigWindow.windows=self.window
    def openLan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = lanConfig.Ui_LanWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        lanConfig.Ui_LanWindow.windows=self.window
    def openWifi(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = wifiConfig.Ui_WifiWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        wifiConfig.Ui_WifiWindow.windows=self.window
    def openDisplay(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = displayConfig.Ui_DisplayWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        displayConfig.Ui_DisplayWindow.windows=self.window
    def openSystem(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = systemConfig.Ui_SystemWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        systemConfig.Ui_SystemWindow.windows=self.window
    def openAccount(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = accountConfig.Ui_AccountWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        accountConfig.Ui_AccountWindow.windows=self.window

    def setupUi(self, SystemWindow):
        SystemWindow.setObjectName("SystemWindow")
        SystemWindow.resize(1280, 800)
        max_x=SystemWindow.width()
        max_y=SystemWindow.height()
        SystemWindow.showFullScreen()
        SystemWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(SystemWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(30, 100, max_x-60, 271))
        self.listView.setObjectName("listView")
        self.lineEdit_delay = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_delay.setGeometry(QtCore.QRect(40, 140, max_x-230, 26))
        self.lineEdit_delay.setObjectName("lineEdit_delay")
        self.label_form = QtWidgets.QLabel(self.centralwidget)
        self.label_form.setGeometry(QtCore.QRect(40, 120, 97, 20))
        self.label_form.setObjectName("label_form")
        self.pb_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pb_delete.setGeometry(QtCore.QRect(40, 210, max_x-80, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_delete.setFont(font)
        self.pb_delete.setObjectName("pb_delete")
        self.pb_delete.clicked.connect(self.showDelete)
        self.pb_device = QtWidgets.QPushButton(self.centralwidget)
        self.pb_device.setGeometry(QtCore.QRect(30, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_device.setFont(font)
        self.pb_device.setObjectName("pb_device")
        self.pb_device.clicked.connect(self.openConfig)

        self.pb_lan = QtWidgets.QPushButton(self.centralwidget)
        self.pb_lan.setGeometry(QtCore.QRect(130, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_lan.setFont(font)
        self.pb_lan.setObjectName("pb_lan")
        self.pb_lan.clicked.connect(self.openLan)

        self.pb_wifi = QtWidgets.QPushButton(self.centralwidget)
        self.pb_wifi.setGeometry(QtCore.QRect(230, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_wifi.setFont(font)
        self.pb_wifi.setObjectName("pb_wifi")
        self.pb_wifi.clicked.connect(self.openWifi)

        self.pb_display = QtWidgets.QPushButton(self.centralwidget)
        self.pb_display.setGeometry(QtCore.QRect(330, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_display.setFont(font)
        self.pb_display.setObjectName("pb_display")
        self.pb_display.clicked.connect(self.openDisplay)


        self.pb_system_active = QtWidgets.QPushButton(self.centralwidget)
        self.pb_system_active.setGeometry(QtCore.QRect(430, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_system_active.setFont(font)
        self.pb_system_active.setObjectName("pb_system_active")

        self.pb_account = QtWidgets.QPushButton(self.centralwidget)
        self.pb_account.setGeometry(QtCore.QRect(530, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_account.setFont(font)
        self.pb_account.setObjectName("pb_account")
        self.pb_account.clicked.connect(self.openAccount)

        self.label_device = QtWidgets.QLabel(self.centralwidget)
        self.label_device.setGeometry(QtCore.QRect(30, 80, max_x-60, 31))
        self.label_device.setObjectName("label_device")
        self.pb_save_delay = QtWidgets.QPushButton(self.centralwidget)
        self.pb_save_delay.setGeometry(QtCore.QRect(max_x-180, 140, 140, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_save_delay.setFont(font)
        self.pb_save_delay.setObjectName("pb_save_delay")
        self.pb_save_delay.clicked.connect(self.showDialog)
        self.label_form_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_form_2.setGeometry(QtCore.QRect(40, 180, max_x-80, 21))
        self.label_form_2.setObjectName("label_form_2")
        self.pb_restart = QtWidgets.QPushButton(self.centralwidget)
        self.pb_restart.setGeometry(QtCore.QRect(40, 280, max_x-80, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_restart.setFont(font)
        self.pb_restart.setObjectName("pb_restart")
        self.pb_restart.clicked.connect(self.showRestart)
        self.label_form_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_form_3.setGeometry(QtCore.QRect(40, 250, 681, 21))
        self.label_form_3.setObjectName("label_form_3")
        SystemWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SystemWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        SystemWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SystemWindow)
        self.statusbar.setObjectName("statusbar")
        SystemWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SystemWindow)
        QtCore.QMetaObject.connectSlotsByName(SystemWindow)
        das01.Ui_MainWindow.setupfooter(self,SystemWindow)

        

    def retranslateUi(self, SystemWindow):
        _translate = QtCore.QCoreApplication.translate
        SystemWindow.setWindowTitle(_translate("SystemWindow", "MainWindow"))
        self.label_form.setText(_translate("SystemWindow", "System Delay"))
        self.pb_delete.setText(_translate("SystemWindow", "Delete LOG"))
        self.pb_device.setText(_translate("SystemWindow", "Device Setting"))
        self.pb_lan.setText(_translate("SystemWindow", "LAN Setting"))
        self.pb_wifi.setText(_translate("SystemWindow", "WiFi Setting"))
        self.pb_display.setText(_translate("SystemWindow", "Display Setting"))
        self.pb_system_active.setText(_translate("SystemWindow", "System"))
        self.pb_account.setText(_translate("SystemWindow", "My Account"))
        self.label_device.setText(_translate("SystemWindow", "  System Setting"))
        self.pb_save_delay.setText(_translate("SystemWindow", "Save"))
        self.label_form_2.setText(_translate("SystemWindow", "Press Delete Log Button to Delete Entire log data"))
        self.pb_restart.setText(_translate("SystemWindow", "Restart Device"))
        self.label_form_3.setText(_translate("SystemWindow", "Press Restart Device Button if you want to reboot DAS Anounciator"))
        cfg= db.readDb.readDataTabel(1,"m_mesin")
        self.lineEdit_delay.setText(str(cfg[0]["system_delay"]))

    def showRestart(self):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setText("Are You Sure restart device")
        msgBox.setWindowTitle("Status Message")  
        msgBox.setIcon(QtWidgets.QMessageBox.Information)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok| QtWidgets.QMessageBox.No )
        returnValue = msgBox.exec()
        #updData(x,tabel,row,val,where,val2):
        if(returnValue==QtWidgets.QMessageBox.Ok):
            db.updDb.updData(1,'power','reboot',1,'id',1)
           # db.delDb.delNotifList(1)
            print(returnValue)

    def showDelete(self):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setText("Are You Sure to Delete Data")
        msgBox.setWindowTitle("Status Message")  
        msgBox.setIcon(QtWidgets.QMessageBox.Information)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok| QtWidgets.QMessageBox.Cancel )
        returnValue = msgBox.exec()
        if(returnValue==QtWidgets.QMessageBox.Ok):
            db.delDb.delNotifList(1)
            print("delete Data")
            
        

    def showDialog(self):
        msgBox = QtWidgets.QMessageBox()
        delay =self.lineEdit_delay.text()
        if len(delay)>0 :
            res=db.updDb.updateDelay(1,delay)
            print(res)
            msgBox.setText("Your Data Has been Saved")
            msgBox.setWindowTitle("Status Message")  
            msgBox.setIcon(QtWidgets.QMessageBox.Information)
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
            returnValue = msgBox.exec()
            
        else:
            msgBox.setText("Your Data is Empty")
            msgBox.setWindowTitle("Status Message")  
            msgBox.setIcon(QtWidgets.QMessageBox.Warning)
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
            returnValue = msgBox.exec()
            print("data is Empty")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SystemWindow = QtWidgets.QMainWindow()
    ui = Ui_SystemWindow()
    ui.setupUi(SystemWindow)
    SystemWindow.show()
    sys.exit(app.exec_())
