# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lanConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import deviceConfig 
import displayConfig 
import wifiConfig 
import systemConfig 
import accountConfig
import das01
import log
import db

class Ui_LanWindow(object):
    windows=None
    def ack(self):
        das01.ack=1
        db.updDb.updData(1,"m_mesin","ack",1,"id",1)
    def mute(self):
        db.updDb.updData(1,"m_mesin","mute",0,"id",1)
    def reset(self):
        das01.ack=0
        db.updDb.rstMesin(1)
    def openLog(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = log.Ui_LogWindow()
        self.ui.setupUi(self.window)
        log.Ui_LogWindow.windows=self.window
       
        self.windows.destroy()
        self.window.show()
    def openHome(self):
        print("gotoHome")
        self.window = QtWidgets.QMainWindow()
        self.ui = das01.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        das01.Ui_MainWindow.windows=self.window
    def openConfig(self):
        self.window = QtWidgets.QMainWindow()
        #print(deviceConfig)
        self.ui = deviceConfig.Ui_ConfigWindow()
        self.ui.setupUi(self.window)
        deviceConfig.Ui_ConfigWindow.windows=self.window
        self.window.show()
        self.windows.destroy()
        self.windows=None
    def openWifi(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = wifiConfig.Ui_WifiWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        wifiConfig.Ui_WifiWindow.windows=self.window
    def openDisplay(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = displayConfig.Ui_DisplayWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        displayConfig.Ui_DisplayWindow.windows=self.window
    def openSystem(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = systemConfig.Ui_SystemWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        systemConfig.Ui_SystemWindow.windows=self.window
    def openAccount(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = accountConfig.Ui_AccountWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        accountConfig.Ui_AccountWindow.windows=self.window

    def setupUi(self, LanWindow):
        LanWindow.setObjectName("LanWindow")
        LanWindow.resize(1280, 800)
        
        max_x=LanWindow.width()
        max_y=LanWindow.height()
        LanWindow.showFullScreen()
        LanWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(LanWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(30, 100, max_x-60, 341))
        self.listView.setObjectName("listView")
        self.lineEdit_server = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_server.setGeometry(QtCore.QRect(40, 160, max_x-80, 26))
        self.lineEdit_server.setObjectName("lineEdit_server")
        self.label_form = QtWidgets.QLabel(self.centralwidget)
        self.label_form.setGeometry(QtCore.QRect(40, 140, 97, 20))
        self.label_form.setObjectName("label_form")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ip.setGeometry(QtCore.QRect(40, 210, max_x-80, 26))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.label_form_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_form_2.setGeometry(QtCore.QRect(40, 190, 97, 20))
        self.label_form_2.setObjectName("label_form_2")
        self.label_form_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_form_3.setGeometry(QtCore.QRect(40, 240, 97, 20))
        self.label_form_3.setObjectName("label_form_3")
        self.lineEdit_netmask = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_netmask.setGeometry(QtCore.QRect(40, 260, max_x-80, 26))
        self.lineEdit_netmask.setObjectName("lineEdit_netmask")
        self.label_form_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_form_4.setGeometry(QtCore.QRect(40, 290, 97, 20))
        self.label_form_4.setObjectName("label_form_4")
        self.lineEdit_gateway = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gateway.setGeometry(QtCore.QRect(40, 310, max_x-80, 26))
        self.lineEdit_gateway.setObjectName("lineEdit_gateway")
        self.pb_save_device = QtWidgets.QPushButton(self.centralwidget)
        self.pb_save_device.setGeometry(QtCore.QRect(40, 400, 191, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_save_device.setFont(font)
        self.pb_save_device.setObjectName("pb_save_device")
        self.pb_save_device.clicked.connect(self.showDialog)
        self.pb_device = QtWidgets.QPushButton(self.centralwidget)
        self.pb_device.setGeometry(QtCore.QRect(30, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_device.setFont(font)
        self.pb_device.setObjectName("pb_device")   
        self.pb_device.clicked.connect(self.openConfig)
        self.pb_lan_active = QtWidgets.QPushButton(self.centralwidget)
        self.pb_lan_active.setGeometry(QtCore.QRect(130, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_lan_active.setFont(font)
        self.pb_lan_active.setObjectName("pb_lan_active")

        self.pb_wifi = QtWidgets.QPushButton(self.centralwidget)
        self.pb_wifi.setGeometry(QtCore.QRect(230, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_wifi.setFont(font)
        self.pb_wifi.setObjectName("pb_wifi")
        self.pb_wifi.clicked.connect(self.openWifi)

        self.pb_display = QtWidgets.QPushButton(self.centralwidget)
        self.pb_display.setGeometry(QtCore.QRect(330, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_display.setFont(font)
        self.pb_display.setObjectName("pb_display")
        self.pb_display.clicked.connect(self.openDisplay)

        self.pb_system = QtWidgets.QPushButton(self.centralwidget)
        self.pb_system.setGeometry(QtCore.QRect(430, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_system.setFont(font)
        self.pb_system.setObjectName("pb_system")
        self.pb_system.clicked.connect(self.openSystem)

        self.pb_account = QtWidgets.QPushButton(self.centralwidget)
        self.pb_account.setGeometry(QtCore.QRect(530, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_account.setFont(font)
        self.pb_account.setObjectName("pb_account")
        self.pb_account.clicked.connect(self.openAccount)
        
        self.label_device = QtWidgets.QLabel(self.centralwidget)
        self.label_device.setGeometry(QtCore.QRect(30, 80, max_x-60, 31))
        self.label_device.setObjectName("label_device")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 120, 141, 17))
        self.checkBox.setObjectName("checkBox")
        self.label_form_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_form_5.setGeometry(QtCore.QRect(40, 340, 97, 20))
        self.label_form_5.setObjectName("label_form_5")
        self.lineEdit_dns = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dns.setGeometry(QtCore.QRect(40, 360, max_x-80, 26))
        self.lineEdit_dns.setObjectName("lineEdit_dns")
        LanWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LanWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        LanWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LanWindow)
        self.statusbar.setObjectName("statusbar")
        LanWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LanWindow)
        QtCore.QMetaObject.connectSlotsByName(LanWindow)
        das01.Ui_MainWindow.setupfooter(self,LanWindow)

    def retranslateUi(self, LanWindow):
        _translate = QtCore.QCoreApplication.translate
        LanWindow.setWindowTitle(_translate("LanWindow", "MainWindow"))
        self.label_form.setText(_translate("LanWindow", "IP Server"))
        self.label_form_2.setText(_translate("LanWindow", "IP ADDRESS"))
        self.label_form_3.setText(_translate("LanWindow", "Netmask"))
        self.label_form_4.setText(_translate("LanWindow", "Gateway"))
        self.pb_save_device.setText(_translate("LanWindow", "Save Configuration"))
        self.pb_device.setText(_translate("LanWindow", "Device Setting"))
        self.pb_lan_active.setText(_translate("LanWindow", "LAN Setting"))
        self.pb_wifi.setText(_translate("LanWindow", "WiFi Setting"))
        self.pb_display.setText(_translate("LanWindow", "Display Setting"))
        self.pb_system.setText(_translate("LanWindow", "System"))
        self.pb_account.setText(_translate("LanWindow", "My Account"))
        self.label_device.setText(_translate("LanWindow", "   LAN Setting "))
        self.checkBox.setText(_translate("LanWindow", "Enable DHCP"))
        self.label_form_5.setText(_translate("LanWindow", "DNS"))
        cfg= db.readDb.readDataTabel(1,"network")
        dhcp=int(cfg[0]["dhcp"])
        if dhcp==1:
            self.checkBox.setChecked(True)
        else:
            self.checkBox.setChecked(False)
        
        self.lineEdit_server.setText(cfg[0]["ipserver"])
        self.lineEdit_ip.setText(cfg[0]["iplocal"])
        self.lineEdit_netmask.setText(cfg[0]["netmask"])
        self.lineEdit_gateway.setText(cfg[0]["gateway"])
        self.lineEdit_dns.setText(cfg[0]["dns"])

    def showDialog(self):
        msgBox = QtWidgets.QMessageBox()
        ipserver    =self.lineEdit_server.text()
        iplocal     =self.lineEdit_ip.text()
        netmask     =self.lineEdit_netmask.text()
        gtw         =self.lineEdit_gateway.text() 
        dns         =self.lineEdit_dns.text()
        dhcp =0
        if self.checkBox.isChecked():
            dhcp=1
        print(ipserver,iplocal,netmask,gtw,dns,dhcp)
      
        if len(ipserver)>0 and len(iplocal)>0 and len(netmask)>0 and len(gtw)>0 and len(dns)>0 :
            db.updDb.updateNetwork(0,ipserver,iplocal,netmask,gtw,dns,dhcp)
            #res=db.updDb.updDeviceConfig(1,nama,lokasi)
            #print(res)
            msgBox.setText("Your Data Has been Saved")
            msgBox.setWindowTitle("Status Message")  
            msgBox.setIcon(QtWidgets.QMessageBox.Information)
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
            returnValue = msgBox.exec()      
        else:
            msgBox.setText("Your Data is Empty")
            msgBox.setWindowTitle("Status Message")  
            msgBox.setIcon(QtWidgets.QMessageBox.Warning)
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
            returnValue = msgBox.exec()
            print("data is Empty")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LanWindow = QtWidgets.QMainWindow()
    ui = Ui_LanWindow()
    ui.setupUi(LanWindow)
    LanWindow.show()
    sys.exit(app.exec_())
