# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import db as db
import das01
import passWindow
from PyQt5 import QtCore, QtGui, QtWidgets
hal =0


class Ui_LogWindow(object):
    windows = None
    def ack(self):
        das01.ack=1
        db.updDb.updData(1,"m_mesin","ack",1,"id",1)
    def mute(self):
        db.updDb.updData(1,"m_mesin","mute",0,"id",1)
    def reset(self):
        das01.ack=0
        db.updDb.rstMesin(1)
    def openHome(self):
        print("gotoHome")
        global hal
        self.window = QtWidgets.QMainWindow()
        self.ui = das01.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.pb_home.destroy()
        self.pb_mute.destroy()
        self.pb_ack.destroy()
        self.pb_reset.destroy()
        self.pb_config.destroy() 
        self.pb_log.destroy()
        self.label.destroy()        
        self.windows.destroy()
        self.window.show()
        hal =0
        das01.Ui_MainWindow.windows=self.window
    def openConfig(self):
        global flagTime
        global hal
        hal =0
        flagTime =2
        self.window = QtWidgets.QMainWindow()
        self.ui = passWindow.Ui_PassWindow()
        self.ui.setupUi(self.window)
        passWindow.Ui_PassWindow.windows=self.window
        passWindow.Ui_PassWindow.windows2=self.windows
        self.window.show()
    def openLog(self):
        print("log")
    def setupUi(self, LogWindow):
        LogWindow.setObjectName("LogWindow")
        LogWindow.showFullScreen()
        LogWindow.resize(1280, 800)
        self.centralwidget = QtWidgets.QWidget(LogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(35, 70, 1260, 500))
        self.tableWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnWidth(0,200)
        self.tableWidget.setColumnWidth(1,200)
        self.tableWidget.setColumnWidth(2,500)
        self.tableWidget.setColumnWidth(3,160)
        self.tableWidget.setColumnWidth(4,150)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.verticalHeader().hide()
        item = QtWidgets.QTableWidgetItem()
        myFont=QtGui.QFont()
        myFont.setBold(True)
        for i in range (15):
            for j in range (5):
                self.tableWidget.setItem(i, j, item)
                if i % 2 == 0:
                    self.tableWidget.item(i, j).setBackground(QtGui.QColor(72,82,83))
                    self.tableWidget.item(i, j).setFont(myFont)
                else :
                    self.tableWidget.item(i, j).setBackground(QtGui.QColor(52,60,68))
                    self.tableWidget.item(i, j).setFont(myFont)
             
                item = QtWidgets.QTableWidgetItem()
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1195, 600, 75, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.next)
       
        self.pushButton_2.setStyleSheet("background-color:gray;color:white;")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1080, 600, 75, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.back)
        self.pushButton_3.setStyleSheet("background-color:gray;color:white;")
        self.label_log = QtWidgets.QLabel(self.centralwidget)
        self.label_log.setGeometry(QtCore.QRect(1170, 600, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_log.setFont(font)
        self.label_log.setObjectName("label_logx")
        self.label_log.setStyleSheet("color:white;")
        LogWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LogWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        LogWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LogWindow)
        self.statusbar.setObjectName("statusbar")
        LogWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LogWindow)
        QtCore.QMetaObject.connectSlotsByName(LogWindow)
        das01.Ui_MainWindow.setupfooter(self,LogWindow)
        
    def next(self):
        global hal
        _translate = QtCore.QCoreApplication.translate
        
       
        hal =hal+1
        log = db.readDb.readLogPage(1,hal)
        if len(log)>0:
            self.label_log.setText(_translate("LogWindow", str(hal+1)))
            for i in range(15):
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("LogWindow","" ))
                item = self.tableWidget.item(i, 1)
                item.setText(_translate("LogWindow", ""))
                item = self.tableWidget.item(i, 2)
                item.setText(_translate("LogWindow",""))
                item = self.tableWidget.item(i, 3)
                item.setText(_translate("LogWindow",""))
                item = self.tableWidget.item(i, 4)
                item.setText(_translate("LogWindow", ""))
            for i in range(len(log)):
                #print (log[i]["nama_mesin"])
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("LogWindow",log[i]["nama_gi"] ))
                item = self.tableWidget.item(i, 1)
                item.setText(_translate("LogWindow", log[i]["nama_mesin"]))
                item = self.tableWidget.item(i, 2)
                item.setText(_translate("LogWindow",log[i]["nama_alat"]))
                item = self.tableWidget.item(i, 3)
                item.setText(_translate("LogWindow", log[i]["status"]))
                item = self.tableWidget.item(i, 4)
                item.setText(_translate("LogWindow", str(log[i]["tanggal"].strftime('%d-%m-%Y %H:%M:%S'))))
        else :
            hal=hal-1
                
    def back(self):
        global hal
        _translate = QtCore.QCoreApplication.translate
        if(hal>0):
            hal =hal-1
            log = db.readDb.readLogPage(1,hal)
            self.label_log.setText(_translate("LogWindow", str(hal+1)))
            for i in range(len(log)):
                #print (log[i]["nama_mesin"])
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("LogWindow",log[i]["nama_gi"] ))
                item = self.tableWidget.item(i, 1)
                item.setText(_translate("LogWindow", log[i]["nama_mesin"]))
                item = self.tableWidget.item(i, 2)
                item.setText(_translate("LogWindow",log[i]["nama_alat"]))
                item = self.tableWidget.item(i, 3)
                item.setText(_translate("LogWindow", log[i]["status"]))
                item = self.tableWidget.item(i, 4)
                item.setText(_translate("LogWindow", str(log[i]["tanggal"].strftime('%d-%m-%Y %H:%M:%S'))))
      


    def retranslateUi(self, LogWindow):
        _translate = QtCore.QCoreApplication.translate
        LogWindow.setWindowTitle(_translate("LogWindow", "LogWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("LogWindow", "1"))
        
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("LogWindow", "Location"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("LogWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("LogWindow", "Channel"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("LogWindow", "Status"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("LogWindow", "Date"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        global hal
        log = db.readDb.readLogPage(1,hal)
        print(len(log))
        for i in range(len(log)):
            item = self.tableWidget.item(i, 0)
            item.setText(_translate("LogWindow",log[i]["nama_gi"] ))
            item = self.tableWidget.item(i, 1)
            item.setText(_translate("LogWindow", log[i]["nama_mesin"]))
            item = self.tableWidget.item(i, 2)
            item.setText(_translate("LogWindow",log[i]["nama_alat"]))
            item = self.tableWidget.item(i, 3)
            item.setText(_translate("LogWindow", log[i]["status"]))
            item = self.tableWidget.item(i, 4)
            item.setText(_translate("LogWindow", str(log[i]["tanggal"].strftime('%d-%m-%Y %H:%M:%S'))))
     
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("LogWindow", "Next"))
        self.pushButton_3.setText(_translate("LogWindow", "Previous"))
        self.label_log.setText(_translate("LogWindow", "1"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogWindow = QtWidgets.QMainWindow()
    ui = Ui_LogWindow()
    ui.setupUi(LogWindow)
    LogWindow.show()
    sys.exit(app.exec_())
