# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accountConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import deviceConfig 
import lanConfig
import displayConfig 
import wifiConfig 
import systemConfig 
import accountConfig
import das01
import log
import db

class Ui_AccountWindow(object):
    windows = None
    def ack(self):
        das01.ack=1
        db.updDb.updData(1,"m_mesin","ack",1,"id",1)
    def mute(self):
        db.updDb.updData(1,"m_mesin","mute",0,"id",1)
    def reset(self):
        das01.ack=0
        db.updDb.rstMesin(1)
    def openLog(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = log.Ui_LogWindow()
        self.ui.setupUi(self.window)
        log.Ui_LogWindow.windows=self.window
        self.windows.destroy()
        self.window.show()
    def openHome(self):
        print("gotoHome")
        self.window = QtWidgets.QMainWindow()
        self.ui = das01.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        das01.Ui_MainWindow.windows=self.window
    def openConfig(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = deviceConfig.Ui_ConfigWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        deviceConfig.Ui_ConfigWindow.windows=self.window
    def openLan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = lanConfig.Ui_LanWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        lanConfig.Ui_LanWindow.windows=self.window
    def openWifi(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = wifiConfig.Ui_WifiWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        wifiConfig.Ui_WifiWindow.windows=self.window
    def openDisplay(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = displayConfig.Ui_DisplayWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        displayConfig.Ui_DisplayWindow.windows=self.window
    def openSystem(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = systemConfig.Ui_SystemWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        systemConfig.Ui_SystemWindow.windows=self.window
    def openAccount(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = accountConfig.Ui_AccountWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.windows.destroy()
        accountConfig.Ui_AccountWindow.windows=self.window

    def setupUi(self, AccountWindow):
        AccountWindow.setObjectName("AccountWindow")
        AccountWindow.resize(1280, 800)
        
        AccountWindow.showFullScreen()
        max_x=AccountWindow.width()
        max_y=AccountWindow.height()
        AccountWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(AccountWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.pb_device = QtWidgets.QPushButton(self.centralwidget)
        self.pb_device.setGeometry(QtCore.QRect(30, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_device.setFont(font)
        self.pb_device.setObjectName("pb_device")
        self.pb_device.clicked.connect(self.openConfig)

        self.pb_lan = QtWidgets.QPushButton(self.centralwidget)
        self.pb_lan.setGeometry(QtCore.QRect(130, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_lan.setFont(font)
        self.pb_lan.setObjectName("pb_lan")
        self.pb_lan.clicked.connect(self.openLan)

        self.pb_wifi = QtWidgets.QPushButton(self.centralwidget)
        self.pb_wifi.setGeometry(QtCore.QRect(230, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_wifi.setFont(font)
        self.pb_wifi.setObjectName("pb_wifi")
        self.pb_wifi.clicked.connect(self.openWifi)

        self.pb_display = QtWidgets.QPushButton(self.centralwidget)
        self.pb_display.setGeometry(QtCore.QRect(330, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_display.setFont(font)
        self.pb_display.setObjectName("pb_display")
        self.pb_display.clicked.connect(self.openDisplay)

        self.pb_system = QtWidgets.QPushButton(self.centralwidget)
        self.pb_system.setGeometry(QtCore.QRect(430, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_system.setFont(font)
        self.pb_system.setObjectName("pb_system")
        self.pb_system.clicked.connect(self.openSystem)

        self.pb_account_active = QtWidgets.QPushButton(self.centralwidget)
        self.pb_account_active.setGeometry(QtCore.QRect(530, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_account_active.setFont(font)
        self.pb_account_active.setObjectName("pb_account_active")
        self.label_device = QtWidgets.QLabel(self.centralwidget)
        self.label_device.setGeometry(QtCore.QRect(30, 80, max_x-60, 31))
        self.label_device.setObjectName("label_device")
        self.label_form_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_form_2.setGeometry(QtCore.QRect(40, 120, 97, 20))
        self.label_form_2.setObjectName("label_form_2")

        # self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        # self.lineEdit_username.setGeometry(QtCore.QRect(40, 140, max_x-80, 26))
        # self.lineEdit_username.setObjectName("lineEdit_username")

        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(30, 100, max_x-60, 120))
        self.listView.setObjectName("listView")
        self.pb_save_account = QtWidgets.QPushButton(self.centralwidget)
        self.pb_save_account.setGeometry(QtCore.QRect(40, 180, 191, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_save_account.setFont(font)
        self.pb_save_account.setObjectName("pb_save_account")
        self.pb_save_account.clicked.connect(self.showDialog)
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(40, 140, max_x-80, 26))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lineEdit_password.setMaxLength(6)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        
        self.lineEdit_password.setValidator(QtGui.QIntValidator())
        # self.label_form = QtWidgets.QLabel(self.centralwidget)
        # self.label_form.setGeometry(QtCore.QRect(40, 120, 97, 20))
        # self.label_form.setObjectName("label_form")
        self.listView.raise_()
        self.pb_device.raise_()
        self.pb_lan.raise_()
        self.pb_wifi.raise_()
        self.pb_display.raise_()
        self.pb_system.raise_()
        self.pb_account_active.raise_()
        self.label_device.raise_()
        self.label_form_2.raise_()
        # self.lineEdit_username.raise_()
        self.pb_save_account.raise_()
        self.lineEdit_password.raise_()
        #self.label_form.raise_()
        AccountWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AccountWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        AccountWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AccountWindow)
        self.statusbar.setObjectName("statusbar")
        AccountWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AccountWindow)
        QtCore.QMetaObject.connectSlotsByName(AccountWindow)
        das01.Ui_MainWindow.setupfooter(self,AccountWindow)

    def retranslateUi(self, AccountWindow):
        _translate = QtCore.QCoreApplication.translate
        AccountWindow.setWindowTitle(_translate("AccountWindow", "MainWindow"))
        self.pb_device.setText(_translate("AccountWindow", "Device Setting"))
        self.pb_lan.setText(_translate("AccountWindow", "LAN Setting"))
        self.pb_wifi.setText(_translate("AccountWindow", "WiFi Setting"))
        self.pb_display.setText(_translate("AccountWindow", "Display Setting"))
        self.pb_system.setText(_translate("AccountWindow", "System"))
        self.pb_account_active.setText(_translate("AccountWindow", "My Account"))
        self.label_device.setText(_translate("AccountWindow", "   Account Setting"))
        self.label_form_2.setText(_translate("AccountWindow", "Password"))
        self.pb_save_account.setText(_translate("AccountWindow", "Save Configuration"))
        cfg= db.readDb.readDataTabel(1,"m_mesin")
        self.lineEdit_password.setText(str(cfg[0]["auth"]))
        #self.label_form.setText(_translate("AccountWindow", "UserName"))
    def showDialog(self):
        msgBox = QtWidgets.QMessageBox()
        auth =self.lineEdit_password.text()
        
        if len(auth)>0 :
            res=db.updDb.updData(1,'m_mesin','auth',f"'{auth}'",'id',1)
            print(res)
            msgBox.setText("Your Data Has been Saved")
            msgBox.setWindowTitle("Status Message")  
            msgBox.setIcon(QtWidgets.QMessageBox.Information)
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
            returnValue = msgBox.exec()
            
        else:
            msgBox.setText("Your Data is Empty")
            msgBox.setWindowTitle("Status Message")  
            msgBox.setIcon(QtWidgets.QMessageBox.Warning)
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
            returnValue = msgBox.exec()
            print("data is Empty")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AccountWindow = QtWidgets.QMainWindow()
    ui = Ui_AccountWindow()
    ui.setupUi(AccountWindow)
    AccountWindow.show()
    sys.exit(app.exec_())
