# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'channel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import db
import das01

class Ui_ChannelWindow(object):
    port =1
    windows =None
    def openHome(self):
        print("gotoHome")
       
        self.window = QtWidgets.QMainWindow()
        self.ui = das01.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.windows.destroy()
        self.window.show()
        das01.Ui_MainWindow.windows=self.window
    def setupUi(self, ChannelWindow):
        ChannelWindow.setObjectName("ChannelWindow")
        ChannelWindow.resize(1280, 800)
        max_x=ChannelWindow.width()
        ChannelWindow.showFullScreen()
        self.centralwidget = QtWidgets.QWidget(ChannelWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 10,  max_x-80, 28))
        self.label_8.setObjectName("label_8")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(30, 40,  max_x-80, 491))
        self.listView.setObjectName("listViewChannel")
        self.lineEditChannel = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditChannel.setGeometry(QtCore.QRect(40, 70,  max_x-80, 26))
        self.lineEditChannel.setObjectName("lineEditChannel")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 50, 97, 20))
        self.label_9.setObjectName("label_9")
        self.lineEditName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditName.setGeometry(QtCore.QRect(40, 130,  max_x-80, 26))
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditName.setMaxLength(50)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 110, 97, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 170, 97, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(40, 230, 97, 20))
        self.label_12.setObjectName("label_12")
        self.lineEditHigh = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditHigh.setGeometry(QtCore.QRect(40, 250,  max_x-80, 26))
        self.lineEditHigh.setObjectName("lineEditHigh")
        self.lineEditHigh.setMaxLength(20)
        self.pushButtonCancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCancel.setGeometry(QtCore.QRect(40, 490, max_x/2, 31))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.pushButtonCancel.clicked.connect(self.cancel)
        self.sliderDelay = QtWidgets.QSlider(self.centralwidget)
        self.sliderDelay.setGeometry(QtCore.QRect(40, 190,  max_x-80, 22))
        self.sliderDelay.setOrientation(QtCore.Qt.Horizontal)
        self.sliderDelay.setObjectName("sliderDelay")
        self.sliderDelay.setMinimum(0)
        self.sliderDelay.setMaximum(10)

        self.lineEditLow = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditLow.setGeometry(QtCore.QRect(40, 320,  max_x-80, 26))
        self.lineEditLow.setObjectName("lineEditLow")
        self.lineEditLow.setMaxLength(20)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(40, 298, 97, 20))
        self.label_13.setObjectName("label_13")
        self.labelDelay = QtWidgets.QLabel(self.centralwidget)
        self.labelDelay.setGeometry(QtCore.QRect(40, 210, 47, 13))
        self.labelDelay.setObjectName("labelDelay")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(40, 370, 97, 20))
        self.label_14.setObjectName("label_14")
        self.lineEditDescription = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDescription.setGeometry(QtCore.QRect(40, 390,  max_x-80, 41))
        self.lineEditDescription.setObjectName("lineEditDescription")
        self.pushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSave.setGeometry(QtCore.QRect(40+(max_x/2), 490, (max_x/2)-80, 31))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonSave.clicked.connect(self.showDialog)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 100, 741, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 221, 741, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(30, 160, 741, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(30, 292, 741, 10))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(30, 360, 741, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(30, 440, 741, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.checkBoxHigh = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxHigh.setGeometry(QtCore.QRect(40, 278, 121, 17))
        self.checkBoxHigh.setObjectName("checkBoxHigh")
        self.checkBoxLow = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxLow.setGeometry(QtCore.QRect(40, 348, 121, 16))
        self.checkBoxLow.setObjectName("checkBoxLow")
        self.checkBoxInvert = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxInvert.setGeometry(QtCore.QRect(40, 460, 121, 16))
        self.checkBoxInvert.setObjectName("checkBoxInvert")
        ChannelWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChannelWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ChannelWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChannelWindow)
        self.statusbar.setObjectName("statusbar")
        ChannelWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChannelWindow)
        QtCore.QMetaObject.connectSlotsByName(ChannelWindow)

    def retranslateUi(self, ChannelWindow):
        
        _translate = QtCore.QCoreApplication.translate
        ChannelWindow.setWindowTitle(_translate("ChannelWindow", "MainWindow"))
        self.label_8.setText(_translate("ChannelWindow", "   Device Detail"))
        self.label_9.setText(_translate("ChannelWindow", "Channel"))
        self.label_10.setText(_translate("ChannelWindow", "Channel Name"))
        self.label_11.setText(_translate("ChannelWindow", "Delay Time"))
        self.label_12.setText(_translate("ChannelWindow", "Status HIGH"))
        self.pushButtonCancel.setText(_translate("ChannelWindow", "CANCEL"))
        self.label_13.setText(_translate("ChannelWindow", "Status LOW"))
        self.label_14.setText(_translate("ChannelWindow", "Description"))
        self.labelDelay.setText(_translate("ChannelWindow", "0"))
        self.pushButtonSave.setText(_translate("ChannelWindow", "SAVE"))
        self.checkBoxHigh.setText(_translate("ChannelWindow", "Send Telegram"))
        self.checkBoxLow.setText(_translate("ChannelWindow", "Send Telegram"))
        self.checkBoxInvert.setText(_translate("ChannelWindow", "Invert"))
        buf=db.readDb.readChannelByPort(1,self.port)
        print(buf)


        self.sliderDelay.setValue(int(buf[0]["delay"]))
        self.labelDelay.setText(_translate("ChannelWindow", str(int(buf[0]["delay"]))))
        self.sliderDelay.valueChanged.connect(self.labelDelay.setNum)
        if(int(buf[0]["tel_high"])==1):
             self.checkBoxHigh.setChecked(True)
        if(int(buf[0]["tel_low"])==1):
             self.checkBoxLow.setChecked(True)
        if(int(buf[0]["invert"])==1):
             self.checkBoxInvert.setChecked(True)
        
        self.lineEditChannel.setText(_translate("ChannelWindow",str(buf[0]["port"])))
        self.lineEditName.setText(_translate("ChannelWindow", buf[0]["nama_alat"]))
        self.lineEditHigh.setText(_translate("ChannelWindow",buf[0]["high"]))
        self.lineEditLow.setText(_translate("ChannelWindow", buf[0]["low"]))
        self.lineEditDescription.setText(_translate("ChannelWindow",buf[0]["detail"] ))
    def cancel(self):
        self.openHome()
    def showDialog(self):
        port = self.lineEditChannel.text()
        name = self.lineEditName.text()
        delay = self.sliderDelay.value()
        high =self.lineEditHigh.text()
        low = self.lineEditLow.text()
        desc = self.lineEditDescription.text()
        check_high = 0
        check_low = 0
        check_invert = 0
        if self.checkBoxHigh.isChecked():
            check_high=1
        if self.checkBoxLow.isChecked():
            check_low=1
        if self.checkBoxInvert.isChecked():
            check_invert=1
        
        msgBox = QtWidgets.QMessageBox()
      
        if len(name)>0 and len(high)>0 and len(low)>0 :
            db.updDb.updateChannelPort(0,name,port,delay,high,low,desc,check_high,check_low,check_invert)
            msgBox.setText("Your Data Has been Saved")
            msgBox.setWindowTitle("Status Message")  
            msgBox.setIcon(QtWidgets.QMessageBox.Information)
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
            returnValue = msgBox.exec()  
            self.openHome()

        else:
            msgBox.setText("Your Data is Empty")
            msgBox.setWindowTitle("Status Message")  
            msgBox.setIcon(QtWidgets.QMessageBox.Warning)
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
            returnValue = msgBox.exec()
            print("data is Empty")
     


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChannelWindow = QtWidgets.QMainWindow()
    ui = Ui_ChannelWindow()
    ui.setupUi(ChannelWindow)
    ChannelWindow.show()
    sys.exit(app.exec_())
